config/routes.rb
Rails.application.routes.draw do

  resources :users
  resource :session

  resources :subs do
    resources :posts, only: [:new, :create, :show]
  end

  resources :posts, only: [:destroy, :edit, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string
#  url        :string
#  content    :string
#  author_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  validates :title, presence: true

  has_many :post_subs

  has_many :subs,
    through: :post_subs,
    source: :sub

  belongs_to :author,
    class_name: :User,
    foreign_key: :author_id

end

app/models/post_sub.rb
# == Schema Information
#
# Table name: post_subs
#
#  id         :integer          not null, primary key
#  post_id    :integer
#  sub_id     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class PostSub < ApplicationRecord
  validates :post_id, :sub_id, presence: true
  validates :post_id, uniqueness: { scope: :sub_id }

  belongs_to :post

  belongs_to :sub

end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string
#  description  :string
#  moderator_id :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ApplicationRecord
  validates :title, :description, :moderator, presence: true
  validates :title, uniqueness: true

  belongs_to :moderator,
    class_name: :User,
    foreign_key: :moderator_id

  has_many :posts

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string
#  password_digest :string
#  session_token   :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :username, :password_digest, :session_token, presence: true
  validates :username, :session_token, uniqueness: true
  validates :password, length: {minimum: 6, allow_nil: true}

  attr_reader :password

  after_initialize :ensure_session_token

  has_many :posts,
    class_name: :Post,
    foreign_key: :author_id

  has_many :moderated_subs,
    class_name: :Sub,
    foreign_key: :moderator_id

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    user && user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    save!
    self.session_token
  end



  def self.find_by_session(session_token)
    User.find_by(session_token: session_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def redirect_unless_logged_in
    redirect_to subs_url unless logged_in?
  end

  def current_user
    @current_user ||= User.find_by_session(session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def login(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :redirect_unless_author, only: [:edit, :update]

  before_action :redirect_unless_author_or_mod, only: :destroy

  def new
    @post = Post.new
    @sub_id = params[:sub_id]
  end

  def create
    @post = Post.new(post_params)
    @post.sub_id = params[:sub_id]
    if @post.save
      redirect_to sub_url(@post.sub_id)
    else
      flash[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @sub = @post.sub
    if @post.update(post_params)
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @sub = @post.sub
    @post.destroy
    redirect_to sub_url(@sub)
  end

  def show
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :url, :content)
  end

  def redirect_unless_author
    @post = Post.find(params[:id])
    if @post.author != current_user
      redirect_to sub_url(@post.sub)
      flash[:errors] = ["Hey you can't do that, man."]
    end
  end

  def redirect_unless_author_or_mod
    @post = Post.find(params[:id])
    unless @post.author == current_user || @post.sub.moderator == current_user
      redirect_to sub_url(@post.sub)
      flash[:errors] = ["Hey you can't do that, man."]
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )
    if user
      login(user)
      redirect_to subs_url
    else
      flash[:errors] = ['Invalid login']
      render :new
    end
  end

  def destroy
    logout!
    redirect_to subs_url
  end

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController

  before_action :redirect_unless_moderator, only: [:edit, :update, :destroy]

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator = current_user
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def index
    @subs = Sub.all
  end

  def show
    @sub = Sub.find(params[:id])
    @posts = @sub.posts
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = Sub.find(params[:id])

    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def destroy
    @sub = Sub.find(params[:id])
    @sub.destroy
    redirect_to subs_url
  end

  def redirect_unless_moderator
    moderator = Sub.find(params[:id]).moderator
    if moderator != current_user
      redirect_to subs_url
      flash[:errors] = ["Hey you can't do that, man."]
    end
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to subs_url
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash[:errors] %>
    <div class="right-nav">
    <% if logged_in? %>
      <form class="" action="<%= session_url %>" method="post">
        <input
          type="hidden"
          name="authenticity_token"
          value="<%= form_authenticity_token %>">
        <input type="hidden" name="_method" value="delete">
        <input type="submit" name="" value="Sign Out">
      </form>
    <% else %>
        <a href="<%= new_session_url %>">Sign In</a> |
        <a href="<%= new_user_url %>">Sign Up</a>
    <% end %>
    </div>

    <%= yield %>

  </body>
</html>

app/views/posts/edit.html.erb
<h1>Edit a Post</h1>

<form class="" action="<%= post_url(@post) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Title
    <input type="text" name="post[title]" value="<%= @post.title %>">
  </label>

  <label>URL
    <input type="text" name="post[url]" value="<%= @post.url %>">
  </label>

  <label>Content
    <textarea name="post[content]"><%= @post.content %></textarea>
  </label>

  <input type="submit" name="" value="Update Post">
</form>

app/views/posts/new.html.erb
<h1>Make a New Post</h1>

<form class="" action="<%= sub_posts_url(@sub_id) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Title
    <input type="text" name="post[title]" value="<%= @post.title %>">
  </label>

  <label>URL
    <input type="text" name="post[url]" value="<%= @post.url %>">
  </label>

  <label>Content
    <textarea name="post[content]">
      <%= @post.content %>
    </textarea>
  </label>

  <input type="submit" name="" value="Create Post">
</form>

app/views/posts/show.html.erb
<h3>
  <a href="<%= sub_url(@post.sub) %>">Back To Sub</a>
</h3>

<h1>
  <a href="<%= @post.url %>"><%= @post.title %></a>
</h1>

<h3><%= @post.content %></h3>

<h4>Author: <%= @post.author.username %></h4>

<a href="<%= edit_post_url(@post) %>">Edit</a>

<form class="" action="<%= post_url(@post) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="delete">
  <input type="submit" name="" value="Delete">
</form>

app/views/subs/edit.html.erb
<h1>Edit Your Sub</h1>
  <form class="" action="<%= sub_url(@sub) %>" method="post">
    <input type="hidden" name="_method" value="patch">
    <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">

    <label>Title
      <input type="text" name="sub[title]" value="<%= @sub.title %>">
    </label>
    <label>Description
      <input type="text" name="sub[description]" value="<%= @sub.description %>">
    </label>
    <input type="submit" name="" value="Update Sub">
</form>

app/views/subs/index.html.erb
<h1>All Subs</h1>
<ul>
  <% @subs.each do |topic| %>
  <li>
    <a href="<%= sub_url(topic.id) %>">
    <%= "#{topic.title} - #{topic.description}" %>
    </a>
  </li>
  <% end %>
</ul>

<a href="<%= new_sub_url %>">Create New Sub</a>

app/views/subs/new.html.erb
<h1>Create a New Sub</h1>
  <form class="" action="<%=subs_url%>" method="post">
    <label>Title
      <input type="text" name="sub[title]" value="<%= @sub.title %>">
    </label>
    <label>Description
      <input type="text" name="sub[description]" value="<%= @sub.description %>">
    </label>
    <input type="submit" name="" value="Create Sub">
</form>

app/views/subs/show.html.erb
<h5>  <a href="<%= subs_url %>">Back To All Subs</a> </h5>


<table>
  <tr>
    <td>
      <h1><span class="embiggen"><%= @sub.title %></span>: <%= @sub.description %></h1>
      <h4 class="moderated">Moderated by: <%= @sub.moderator.username %></h4>
    </td>
  </tr>
  <tr>
    <td>
      <a href="<%= edit_sub_url(@sub) %>">Edit Sub</a>
    </td>
    <td>
      <form class="" action="<%= sub_url(@sub) %>" method="post">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="hidden" name="_method" value="delete">
        <input type="submit" name="" value="Delete Sub">
      </form>
    </td>
  </tr>
</table>

<div>
  <% @posts.each do |post| %>
  <ul class="reddit-post">
    <li>
      <a href="<%= post.url %>"><%= post.title %></a>
    </li>
    <li>
      <%= post.content %>
    </li>
    <li>
      author: <%= post.author.username %>
    </li>
    <li>
      <a href="<%= sub_post_url(post.sub.id, post.id) %>">show post/comments</a>
    </li>
  </ul>
  <% end %>
</div>

app/views/users/new.html.erb
<h2>Sign Up!</h2>

<form class="" action="<%= users_url %>" method="post">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label>Username
    <input type="text" name="user[username]" value="">
  </label>

  <label>Password
    <input type="password" name="user[password]" value="">
  </label>

  <input type="submit" name="" value="Create User">

</form>